import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    flexDirection: "row",
    backgroundColor: "#fff",
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
});

interface Props {
  text?: string;
}

export default async function SampleDocument() {
  return (
    <Document>
      <Page style={styles.page}>
        <View style={styles.section}>
          <Text>
            This is a PDF generated by @react-pdf/renderer in a Next.js app!
          </Text>
        </View>
      </Page>
    </Document>
  );
}
