import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#fff",
    fontFamily: "PatronWEB",
  },

  section: {
    flexGrow: 1,
    padding: 15,
  },

  pageNumber: {
    position: "absolute",
    fontSize: 12,
    paddingVertical: 40,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "#fff",
    backgroundColor: "red",
  },
  pageTitle: {
    fontSize: 18,
    paddingVertical: 40,
    fontWeight: "bold",
    fontFamily: "PatronWEB-Bold",
  },

  ticket: {
    // flexGrow: 1,
    borderWidth: 1,
    width: "60%",
    borderColor: "#DDDDE4",
    alignSelf: "center",
    margin: 10,
  },

  ticketQr: {
    width: "150px",
    height: "150px",
    alignSelf: "center",
    margin: 20,
  },

  line: {
    paddingVertical: 10,
  },

  lineHeading: {
    fontSize: 12,
    color: "#6B7790",
  },

  descriptionText: {
    fontSize: 10,
    color: "#6B7790",
  },

  lineBigText: {
    fontSize: 18,
    color: "#292c33",
    fontFamily: "PatronWEB-Bold",
  },

  lineText: {
    fontSize: 14,
    color: "#292c33",
    fontFamily: "PatronWEB-Bold",
    textTransform: "capitalize",
  },

  spacer: {
    height: 10,
  },

  separatorContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
  },

  separator: {
    flex: 1,
    height: "0.5px",
    backgroundColor: "#DDDDE4",
  },

  separatorCard: {
    padding: 10,
    paddingHorizontal: 20,
    borderWidth: "0.5px",
    borderColor: "#DDDDE4",
    borderRadius: 30,
    fontSize: 12,
    fontFamily: "PatronWEB-Bold",
  },
});

const PdfDocument: React.FC = () => (
  <Document>
    <Page style={styles.page}>
      <View style={styles.section}>
        <Text>
          This is a PDF generated by @react-pdf/renderer in a Next.js app!
        </Text>
      </View>
    </Page>
  </Document>
);

export default PdfDocument;
